services:
  backend:
    build: ./xuiSubServer
    container_name: exprimental_pcpos_system_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - /etc/x-ui/:/etc/x-ui/

